spring:
  application:
    name: Petter
  data:
    mongodb:
      authentication-database: admin
      database: petterDB
      host: localhost
      port: 27017
      password: admin
      username: admin
      auto-index-creation: true

authorization:
  enabled: true
  secret: TESTSECRETTESTSECRETTESTSECRETTESTSECRETTESTSECRETTESTSECRETTESTSECRETTESTSECRET
  scheme-name: bearerAuth

photo-storage:
  path: ./photo-storage