version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  server:
    container_name: server
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongo