name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew

    - name: Run unit tests
      run: cd android && ./gradlew testDebugUnitTest

  build:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew

    - name: Build with Gradle
      run: cd android && ./gradlew assembleDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
